version: '3.8'

services:
  api:
     container_name: backend-container
     image: skillmastery-backend:v1
     build: .
     ports:
       - 80:80
     networks:
       - skillmastery-network

volumes:
  postgres_data:

networks:
  skillmastery-network:
    driver: bridge