# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App -

env:
  AZURE_WEBAPP_NAME: SkillMastery
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: secrets
    steps:
    - uses: actions/checkout@v2
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker-compose build
    - name: Tagin back
      run: docker tag skillmastery-backend:v1 ${{secrets.DOCKER_HUB_USERNAME}}/skillmastery:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}
    - name: Push to
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/skillmastery:v${{ secrets.BACKEND_MAJOR }}.${{ secrets.BACKEND_MINOR }}
    - name: Tagin frontend with latest
      run: docker tag skillmastery-backend:v1 ${{secrets.DOCKER_HUB_USERNAME}}/skillmastery:latest
    - name: Push to docker hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/skillmastery:latest 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: secrets
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.AZURE_WEBAPP_NAME }}'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: ${{secrets.DOCKER_HUB_USERNAME}}/skillmastery:latest 
